djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from uploadapp.views import UploadCreateView

urlpatterns = [
    path('', UploadCreateView.as_view()),


    path('admin/', admin.site.urls),
    path('uploads/', include('uploadapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uploadapp/urls.py
from django.urls import path

from uploadapp.views import UploadCreateView, UploadUpdateView,GeneratePDF2

app_name = 'uploadapp'

urlpatterns = [
    path('create/', UploadCreateView.as_view(), name='create'),
    path('update/<int:pk>', UploadUpdateView.as_view(), name='update'),
    path('pdf2/<int:pk>', GeneratePDF2.as_view(), name='pdf2'),
]

uploadapp/models.py
from django.db import models

class Upload(models.Model):
    name = models.CharField(max_length=15, null=True)
    phone_number = models.CharField(max_length=50, null=True)
    image = models.ImageField(upload_to='upload/', null=True)
    location = models.TextField(null=True)
    #type = models.CharField(max_length=30,null=True)
    submit = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True, null=True)
    label = models.TextField(null=True)
    price = models.IntegerField(null=True)

uploadapp/forms.py
from django import forms
from django.forms import ModelForm, TextInput, FileInput, Textarea, HiddenInput

from uploadapp.models import Upload


class UploadCreationForm(ModelForm):

    class Meta:
        model = Upload
        fields = ['name', 'phone_number', 'image', 'location']
        widgets = {
            'name': TextInput(attrs={
                'class': "form-control p-1",
                'style': "",
                'placeholder': "name"
            }),
            'phone_number': TextInput(attrs={
                'class': "form-control p-1",
                'style': "",
                'placeholder': "010-0000-0000 형식으로 기입해주세요"
            }),
            'image': FileInput(attrs={
                'class': "form-control p-1",
                'style': "",
                'placeholder': "file"
            }),
            'location': HiddenInput(attrs={
                'class': "form-control p-1",
                'id': 'geolocation',
                'style': "",
                'placeholder': "위치"
            }),
        }

uploadapp/views.py
# Create your views here.
import os

from django.http import HttpResponse, FileResponse, Http404
from django.template.loader import get_template
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView
from django.views.generic.edit import FormMixin

from uploadapp.forms import UploadCreationForm
from uploadapp.models import Upload

import tensorflow as tf

import googlemaps

import tensorflow as tf
import numpy as np
from PIL import Image
import warnings

import pdfcrowd
import sys
import base64

gmaps = googlemaps.Client(key='AIzaSyCCpe1QXfMoezcFO-eCX4Su_XDRwFuu3nQ')


class UploadCreateView(CreateView):
    model = Upload
    form_class = UploadCreationForm
    template_name = 'uploadapp/create.html'

    def form_valid(self, form):
        temp_upload = form.save(commit=False)
        temp_upload.save()

        temp_upload = form.save(commit=False)
        path = 'media/' + str(temp_upload.image)
        img = Image.open(path)
        result = trash_pred(img)

        temp_upload.price = separ_price(result)
        temp_upload.label = result


        # g = gmaps.reverse_geocode((form.data.get('location')), language='ko')
        form.instance.location = '서울시 관악구' #g[0]['formatted_address']

        temp_upload.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('uploadapp:update', kwargs={'pk': self.object.pk})


class UploadUpdateView(UpdateView):
    model = Upload
    form_class = UploadCreationForm
    context_object_name = 'target_upload'
    template_name = 'uploadapp/update.html'

    def form_valid(self, form):
        temp_upload = form.save(commit=False)
        temp_upload.save()

        temp_upload = form.save(commit=False)
        path = 'media/' + str(temp_upload.image)
        img = Image.open(path)
        result = trash_pred(img)

        temp_upload.price = separ_price(result)
        temp_upload.label = result


        temp_upload.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('uploadapp:update', kwargs={'pk': self.object.pk})


class UploadDetailView(DetailView):
    def get(self, request, *args, **kwargs):
        upload = Upload.objects.get(pk=kwargs['pk'])
        upload.submit = True
        upload.save()
        return super().get(request, *args, **kwargs)

    model = Upload
    context_object_name = 'target_upload'
    template_name = 'uploadapp/detail.html'


class GeneratePDF2(View, FormMixin):

    model = Upload
    context_object_name = 'qs'
    success_url = reverse_lazy('uploadapp:create')

    def get(self, request, *args, **kwargs):
        template = get_template('uploadapp/detail.html')
        qs = Upload.objects.get(pk=kwargs['pk'])

        path = 'media/' + str(qs.image)
        filename = os.path.splitext('./test.zip')[1]

        with open(path, 'rb') as img:
            base64_string = base64.b64encode(img.read())
            tmp = "data:image/"+filename[1:]+";base64," + str(base64_string)[2:-1]
        context = {'qs': qs, 'tmp': tmp}
        html = template.render(context)

        try:
            # create the API client instance
            client = pdfcrowd.HtmlToPdfClient('aksghk1', 'a44f9b773c47f1d593af0d3d384ca957')

            # run the conversion and write the result into the output stream
            client.convertStringToFile(html, f'media/upload/{qs.pk}.pdf')

        except pdfcrowd.Error as why:
            # report the error
            sys.stderr.write('Pdfcrowd Error: {}\n'.format(why))

            # rethrow or handle the exception
            raise

        try:
            return FileResponse(open(f'media/upload/{qs.pk}.pdf', 'rb'), content_type='application/pdf')
        except FileNotFoundError:
            raise Http404()


def trash_pred(img):
    warnings.filterwarnings(action='ignore')
    new_model = tf.keras.models.load_model('my_model/keras_64%.h5')
    label_filter = ['침대', '밥상', '서랍장', '수납장', '의자', '선풍기', '냉장고', '장농', '책상', '소파']

    images = []

    img_resized = img.resize([112, 112])
    pixels = np.array(img_resized)
    images.append(pixels)
    X = np.asarray(images, dtype=np.float32)
    xhat = X / 255.0
    yhat = new_model.predict(xhat)
    return label_filter[np.argmax(yhat)]


def separ_price(result):
    label_filter = ['침대', '밥상', '서랍장', '수납장', '의자', '선풍기', '냉장고', '장농', '책상', '소파']
    if result == label_filter[0]:
        return 11000
    if result == label_filter[1]:
        return 4000
    if result == label_filter[2]:
        return 7000
    if result == label_filter[3]:
        return 8000
    if result == label_filter[4]:
        return 3000
    if result == label_filter[5]:
        return 3000
    if result == label_filter[6]:
        return 10000
    if result == label_filter[7]:
        return 10000
    if result == label_filter[8]:
        return 7000
    if result == label_filter[9]:
        return 13000

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR'">


{% block content %}
{% endblock %}


</body>
</html>

templates/head.html
{% load static %}

<head>

    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>대형 폐기물 처리</title>

    {#  BOOTSTRAP LINK  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {# UTF-8 구분  #}

    {#  GOOGLE FONTS LINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

    {#  DEFAULT CSS LINK  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  MATERIAL ICONS LINK  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>


</head>

uploadapp/templates/uploadapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}

    <div class="mw-500 m-auto">
        <div class="m-5 text-center">
            <h4>대형 폐기물 배출</h4>
        </div>
        <div>
            <form action="{% url 'uploadapp:create' %}"
                  enctype="multipart/form-data"
                  method="post">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                <div class="m-5 text-center">
                    <input type="submit"
                       class="btn btn-info rounded-pill px-5" value="확인하기">
                    <input type="hidden" name="update_pk" value="{{ Up.pk }}">
                </div>
            </form>
        </div>
    </div>

    <script src="{% static 'js/geolocation.js' %}"></script>
{% endblock %}

uploadapp/templates/uploadapp/detail.html
{% extends 'base.html' %}

{% block content %}
<style>

.Thead>tbody>tr:first-child td, .Thead>tbody>tr:first-child th {
    border-top: 2px solid #848cd6;
}

.tbl tbody th {
    background: #f2f6f9;
    font-weight: normal;
}

.tbl td, .tbl th {
    padding: 12px 10px;
    border: 1px solid #e2e2e4;
    line-height: 18px;
    vertical-align: middle;
    box-sizing: border-box;
    font-size: 1rem;
    word-break: break-all;
}

.tbl th {
    text-align: center;
    font-weight: 600;
}

.w25 {
    width: 25% !important;
}

.w35{
    width: 35% !important;
}

col {
    display: table-column;
}

table {
    border-collapse: collapse;
    font-size: 100%;
}

.mT10 {
    margin-top: 10px !important;
}

.mT30 {
    margin-top: 30px !important;
}

.table>:not(:last-child)>:last-child>* {
    border-bottom-color: #e2e2e4;
}

.mw-600 {
    max-width: 600px;
    padding: 1rem 1.5rem;
}

.mTB50 {
    margin-top: 50px !important;
    margin-bottom: 50px; !important;
}

.profile_image{
    height: 200px;
    width: 200px;
    object-fit: scale-down;
}
</style>

    <div class="text-center mw-600 m-auto">
        <h2 class="mTB50">
            대형 폐기물 처리 신청서
        </h2>
        <table class="table tbl Thead mT10">
            <colgroup>
                <col class="w25">
                <col>
            </colgroup>
            <tbody>
                <tr>
                    <th scope="row">
                        이름
                    </th>
                    <td>
                        {{ qs.name }}
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        연락처
                    </th>
                    <td>
                        {{ qs.phone_number }}
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        신청일자
                    </th>
                    <td>
                        {{ qs.created_at }}
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        배출주소
                    </th>
                    <td>
                        {{ qs.location }}
                    </td>
                </tr>
            </tbody>
        </table>
        <p class="mT10">※ 수거를 위해 집안(실내 및 대문 안)으로 들어가지 않습니다.</p>
        <table class="table tbl Thead mT30">
            <colgroup>
                <col class="w35">
                <col>
            </colgroup>
            <tbody>
                <tr>
                    <td rowspan="2">
                        <img src="{{ tmp }}"
                             class="profile_image"
                             id="img"
                             alt="image file">
                    </td>
                    <th scope="row" height="60px">
                        폐기물명
                    </th>
                </tr>
                <tr>
                    <td>
                        {{ qs.label }}
                    </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th scope="row">
                        수수료
                    </th>
                    <td colspan="5">
                        {{ qs.price }} 원
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

{% endblock %}

uploadapp/templates/uploadapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div class="mw-500 m-auto">
        <div class="m-5">
            <h4>대형 폐기물 배출</h4>
        </div>
        <div>
            <form action="{% url 'uploadapp:update' pk=target_upload.pk %}"
                  enctype="multipart/form-data"
                  method="post">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}

                <div class="m-5 text-center">
                    <input type="submit"
                       class="btn btn-info rounded-pill px-5" value="확인하기">
                </div>

            </form>
        </div>
         <div class="container text-center mw-500 m-auto">
             <table class="table tbl Thead mT10">
                <colgroup>
                    <col class="">
                    <col>
                </colgroup>
                <tbody>
                    <tr>
                        <th scope="row">
                            이름
                        </th>
                        <td>
                            {{ target_upload.name }}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            연락처
                        </th>
                        <td>
                            {{ target_upload.phone_number }}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            신청일자
                        </th>
                        <td>
                            {{ target_upload.created_at }}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            배출주소
                        </th>
                        <td>
                            {{ target_upload.location }}
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <img src="{{ target_upload.image.url }}"
                                 class="profile_image"
                                 alt="upload image">
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            종류
                        </th>
                        <td>
                            {{ target_upload.label }}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            수수료
                        </th>
                        <td>
                            {{ target_upload.price }} 원
                        </td>
                    </tr>
                </tbody>
             </table>
         </div>
        <div class="text-center">
            <a href="{% url 'uploadapp:pdf2' pk=target_upload.pk %}"
                class="btn btn-dark rounded-pill px-5 m-5">
                제출하기
            </a>
        </div>
    </div>


{% endblock %}